### ISSUE TITLE
ปัญหา วันที่ 29 กุมภา

### ISSUE THREAD

**Issue by firdows** [dixonsatit/yii2-thai-year-formatter#2]
เจอปัญหา ปัญหา วันที่ 29 กุมภา  มันแสดงเป็นวันที่ 1 มีนา  สามารถแก้ไขได้ไหมครับ

**Comment by firdows** [comment]
ได้วีธีการแปลงแล้ว  ดัดแปลงจากเดิมนิดหน่อย

`

    public function asDate($value, $format = null)
    {
        if ($format === null) {
            $format = $this->dateFormat;
        }
        $year = $this->formatDateTimeValue($value, "php:Y", 'date');
        return $this->replaceYears($this->formatDateTimeValue($value, $format, 'date'), $year);
    }

    public function asDatetime($value, $format = null)
    {
        if ($format === null) {
            $format = $this->datetimeFormat;
        }
        $year = $this->formatDateTimeValue($value, "php:Y", 'date');
        return $this->replaceYears($this->formatDateTimeValue($value, $format, 'datetime'), $year);
    }


    public function replaceYears($strDate, $year)
    {
        return str_replace(['ค.ศ.', $year], ['พ.ศ.', ($year + 543)], $strDate);
    }

`

**Comment by dixonsatit** [comment]
ทำ pull request มาเลยครับเดี๋ยวผม merge ให้

**Comment by firdows** [comment]
จัดไปครับ  แก้ไขและส่งคำขอไปแล้วครับ

**Comment by dixonsatit** [comment]
ผมออก tag และ packagist default เป็น 0.9.8 ให้เรียบร้อยแล้วครับ download ล่าสุดจะเป็นตัวที่แก้นี้เลย @firdows
